// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lista12.Data;

#nullable disable

namespace lista12.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240119013929_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lista12.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Filename = "puppy1.jpg",
                            Name = "article1",
                            Price = 12f
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Filename = "puppy2.jpg",
                            Name = "article2",
                            Price = 2f
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Filename = "puppy3.jpg",
                            Name = "article3",
                            Price = 24f
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Filename = "puppy4.jpg",
                            Name = "article4",
                            Price = 3f
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Filename = "puppy5.jpg",
                            Name = "article5",
                            Price = 42f
                        });
                });

            modelBuilder.Entity("lista12.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "category1"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "category2"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "category3"
                        });
                });

            modelBuilder.Entity("lista12.Models.Article", b =>
                {
                    b.HasOne("lista12.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("lista12.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
